// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfdzjogusxidkiypssrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZHpqb2d1c3hpZGtpeXBzc3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTQ0NjcsImV4cCI6MjA2OTUzMDQ2N30.T7rmNqrjJ4GfUIPU5jkUA-Dsr5WtzMUyC5Aka8w6XXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});